# List Comprehensions Lab

Complete the following set of exercises to solidify your knowledge of list comprehensions.

In [3]:
import os
import numpy as np
import pandas as pd

### 1. Use a list comprehension to create and print a list of consecutive integers starting with 1 and ending with 50.

In [2]:
m = [e for e in range(1,50)]
m

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49]

### 2. Use a list comprehension to create and print a list of even numbers starting with 2 and ending with 200.

In [3]:
p = [ e for e in range(2,200) if e%2==0]
p

[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198]

### 3. Use a list comprehension to create and print a list containing all elements of the 10 x 4 Numpy array below.

In [6]:
a = np.array([[0.84062117, 0.48006452, 0.7876326 , 0.77109654],
       [0.44409793, 0.09014516, 0.81835917, 0.87645456],
       [0.7066597 , 0.09610873, 0.41247947, 0.57433389],
       [0.29960807, 0.42315023, 0.34452557, 0.4751035 ],
       [0.17003563, 0.46843998, 0.92796258, 0.69814654],
       [0.41290051, 0.19561071, 0.16284783, 0.97016248],
       [0.71725408, 0.87702738, 0.31244595, 0.76615487],
       [0.20754036, 0.57871812, 0.07214068, 0.40356048],
       [0.12149553, 0.53222417, 0.9976855 , 0.12536346],
       [0.80930099, 0.50962849, 0.94555126, 0.33364763]])

In [35]:
p = [e for e in a]
p

[array([0.84062117, 0.48006452, 0.7876326 , 0.77109654]),
 array([0.44409793, 0.09014516, 0.81835917, 0.87645456]),
 array([0.7066597 , 0.09610873, 0.41247947, 0.57433389]),
 array([0.29960807, 0.42315023, 0.34452557, 0.4751035 ]),
 array([0.17003563, 0.46843998, 0.92796258, 0.69814654]),
 array([0.41290051, 0.19561071, 0.16284783, 0.97016248]),
 array([0.71725408, 0.87702738, 0.31244595, 0.76615487]),
 array([0.20754036, 0.57871812, 0.07214068, 0.40356048]),
 array([0.12149553, 0.53222417, 0.9976855 , 0.12536346]),
 array([0.80930099, 0.50962849, 0.94555126, 0.33364763])]

### 4. Add a condition to the list comprehension above so that only values greater than or equal to 0.5 are printed.

In [31]:
m = a[a>=0.5]
p = [e for e in m]
p

[0.84062117,
 0.7876326,
 0.77109654,
 0.81835917,
 0.87645456,
 0.7066597,
 0.57433389,
 0.92796258,
 0.69814654,
 0.97016248,
 0.71725408,
 0.87702738,
 0.76615487,
 0.57871812,
 0.53222417,
 0.9976855,
 0.80930099,
 0.50962849,
 0.94555126]

### 5. Use a list comprehension to create and print a list containing all elements of the 5 x 2 x 3 Numpy array below.

In [32]:
b = np.array([[[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]],

       [[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]],

       [[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]],

       [[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]],

       [[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]]])

In [36]:
p = [e for e in b]
p

[array([[0.55867166, 0.06210792, 0.08147297],
        [0.82579068, 0.91512478, 0.06833034]]),
 array([[0.05440634, 0.65857693, 0.30296619],
        [0.06769833, 0.96031863, 0.51293743]]),
 array([[0.09143215, 0.71893382, 0.45850679],
        [0.58256464, 0.59005654, 0.56266457]]),
 array([[0.71600294, 0.87392666, 0.11434044],
        [0.8694668 , 0.65669313, 0.10708681]]),
 array([[0.07529684, 0.46470767, 0.47984544],
        [0.65368638, 0.14901286, 0.23760688]])]

### 5. Add a condition to the list comprehension above so that the last value in each subarray is printed, but only if it is less than or equal to 0.5.

In [37]:
m = b[b<=0.5]
l = [e for e in m]
l


[0.06210792,
 0.08147297,
 0.06833034,
 0.05440634,
 0.30296619,
 0.06769833,
 0.09143215,
 0.45850679,
 0.11434044,
 0.10708681,
 0.07529684,
 0.46470767,
 0.47984544,
 0.14901286,
 0.23760688]

### 6. Use a list comprehension to select and print the names of all CSV files in the */data* directory.

In [42]:
root = "../data"

csv_files = [e for e in os.listdir(root) if e.endswith('.csv') ]
csv_files

['sample_file_5.csv',
 'sample_file_4.csv',
 'sample_file_7.csv',
 'sample_file_8.csv',
 'sample_file_2.csv',
 'sample_file_0.csv',
 'sample_file_9.csv',
 'sample_file_3.csv',
 'sample_file_1.csv',
 'sample_file_6.csv']

### 7. Use a list comprehension and the Pandas `read_csv` and `concat` methods to read all CSV files in the */data* directory and combine them into a single data frame. Display the top 10 rows of the resulting data frame.

In [65]:
import glob

f = os.path.join(root, '*.csv')
csv_files = glob.glob(f) 

m = []
p = [m.append(pd.read_csv(e)) for e in csv_files]
df = pd.concat(m)
df.head(10)

0         1         2         3         4         5         6  \
0  0.437114  0.156941  0.183148  0.817785  0.747632  0.726855  0.944758   
1  0.213337  0.503490  0.802663  0.443484  0.700893  0.129329  0.007176   
2  0.625692  0.184609  0.120652  0.410955  0.408272  0.686792  0.480168   
3  0.642007  0.175592  0.476889  0.451096  0.803491  0.272613  0.576037   
4  0.809129  0.549374  0.055405  0.857802  0.760688  0.662257  0.453289   
0  0.901381  0.790944  0.596603  0.354721  0.357002  0.321325  0.738398   
1  0.763823  0.537281  0.708804  0.975269  0.053777  0.957740  0.389137   
2  0.571864  0.386243  0.567476  0.509283  0.552594  0.173807  0.229092   
3  0.956168  0.422274  0.121713  0.685208  0.713370  0.416245  0.337151   
4  0.121826  0.237479  0.553956  0.173660  0.354423  0.532080  0.271361   

          7         8         9        10        11        12        13  \
0  0.287449  0.792692  0.080025  0.079886  0.067887  0.543498  0.711158   
1  0.027735  0.427692  0.156926  0.486138  0.571278  0.940414  0.940730   
2  0.286901  0.320112  0.048815  0.768725  0.461014  0.090451  0.720938   
3  0.774269  0.323313  0.349850  0.413465  0.641111  0.841210  0.668661   
4  0.658329  0.973615  0.449771  0.615229  0.467290  0.158077  0.305716   
0  0.777885  0.775623  0.717817  0.788198  0.962214  0.394465  0.878922   
1  0.689829  0.510885  0.737445  0.097678  0.242906  0.073603  0.497591   
2  0.257945  0.313437  0.418311  0.750007  0.604759  0.234886  0.832337   
3  0.570693  0.435938  0.360098  0.037437  0.167545  0.847880  0.773456   
4  0.766006  0.607020  0.197302  0.526352  0.676571  0.473574  0.953228   

         14        15        16        17        18        19  
0  0.960030  0.810807  0.579395  0.660811  0.520295  0.945250  
1  0.933377  0.427869  0.654402  0.407580  0.122453  0.115311  
2  0.192501  0.219077  0.034113  0.858956  0.816036  0.582192  
3  0.101031  0.972135  0.479581  0.149982  0.035150  0.528075  
4  0.730355  0.412336  0.469142  0.078734  0.448741  0.827487  
0  0.084206  0.680941  0.992897  0.267455  0.212403  0.572150  
1  0.798467  0.789078  0.947559  0.631497  0.057953  0.060306  
2  0.421263  0.455785  0.893841  0.726412  0.458360  0.048740  
3  0.490628  0.544232  0.954668  0.567280  0.571539  0.560742  
4  0.413186  0.957242  0.642558  0.351496  0.547297  0.177401

### 8. Use a list comprehension to select and print the column numbers for columns from the data set whose median is less than 0.48.

In [77]:
c2 = np.mean(df)

df2 = [e for e in c2 if e<0.48]
df2

[0.4762788721830816,
 0.47179985623470494,
 0.45914042232125346,
 0.4365242297291135]

### 9. Use a list comprehension to add a new column (20) to the data frame whose values are the values in column 19 minus 0.1. Display the top 10 rows of the resulting data frame.

In [78]:
df["20"] = df["19"] - 0.1

df.head(10)

0         1         2         3         4         5         6  \
0  0.437114  0.156941  0.183148  0.817785  0.747632  0.726855  0.944758   
1  0.213337  0.503490  0.802663  0.443484  0.700893  0.129329  0.007176   
2  0.625692  0.184609  0.120652  0.410955  0.408272  0.686792  0.480168   
3  0.642007  0.175592  0.476889  0.451096  0.803491  0.272613  0.576037   
4  0.809129  0.549374  0.055405  0.857802  0.760688  0.662257  0.453289   
0  0.901381  0.790944  0.596603  0.354721  0.357002  0.321325  0.738398   
1  0.763823  0.537281  0.708804  0.975269  0.053777  0.957740  0.389137   
2  0.571864  0.386243  0.567476  0.509283  0.552594  0.173807  0.229092   
3  0.956168  0.422274  0.121713  0.685208  0.713370  0.416245  0.337151   
4  0.121826  0.237479  0.553956  0.173660  0.354423  0.532080  0.271361   

          7         8         9  ...        11        12        13        14  \
0  0.287449  0.792692  0.080025  ...  0.067887  0.543498  0.711158  0.960030   
1  0.027735  0.427692  0.156926  ...  0.571278  0.940414  0.940730  0.933377   
2  0.286901  0.320112  0.048815  ...  0.461014  0.090451  0.720938  0.192501   
3  0.774269  0.323313  0.349850  ...  0.641111  0.841210  0.668661  0.101031   
4  0.658329  0.973615  0.449771  ...  0.467290  0.158077  0.305716  0.730355   
0  0.777885  0.775623  0.717817  ...  0.962214  0.394465  0.878922  0.084206   
1  0.689829  0.510885  0.737445  ...  0.242906  0.073603  0.497591  0.798467   
2  0.257945  0.313437  0.418311  ...  0.604759  0.234886  0.832337  0.421263   
3  0.570693  0.435938  0.360098  ...  0.167545  0.847880  0.773456  0.490628   
4  0.766006  0.607020  0.197302  ...  0.676571  0.473574  0.953228  0.413186   

         15        16        17        18        19        20  
0  0.810807  0.579395  0.660811  0.520295  0.945250  0.845250  
1  0.427869  0.654402  0.407580  0.122453  0.115311  0.015311  
2  0.219077  0.034113  0.858956  0.816036  0.582192  0.482192  
3  0.972135  0.479581  0.149982  0.035150  0.528075  0.428075  
4  0.412336  0.469142  0.078734  0.448741  0.827487  0.727487  
0  0.680941  0.992897  0.267455  0.212403  0.572150  0.472150  
1  0.789078  0.947559  0.631497  0.057953  0.060306 -0.039694  
2  0.455785  0.893841  0.726412  0.458360  0.048740 -0.051260  
3  0.544232  0.954668  0.567280  0.571539  0.560742  0.460742  
4  0.957242  0.642558  0.351496  0.547297  0.177401  0.077401  

[10 rows x 21 columns]

### 10. Use a list comprehension to extract and print all values from the data set that are between 0.7 and 0.75.

In [97]:

df3= [df[str(e)].value_counts() for e in df if 0.7 < df[str(e)].value_counts()< 0.75 ]
df3

TypeError: '<' not supported between instances of 'float' and 'list'